/*.$file${..::User::src::blink.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: my_qpc_Blink.qm
* File:  ${..::User::src::blink.c}
*
* This code has been generated by QM 5.1.1 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${..::User::src::blink.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "blink.h"

/* instantiate the Blinky active object ------------------------------------*/
static Blink l_blink;
QActive * const AO_Blink = &l_blink.super;


/*================ ask QM to define the Blinky class ================*/
/*.$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*. Check for the minimum required QP version */
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.9.0 or higher required
#endif
/*.$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${AOs::Blink} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::Blink} ...........................................................*/
/*.${AOs::Blink::SM} .......................................................*/
QState Blink_initial(Blink * const me, void const * const par) {
    /*.${AOs::Blink::SM::initial} */
    (void)par; /* unused parameter */
    /* arm the private time event to expire in 1/2s
    * and periodically every 1/2 second
    */
    QTimeEvt_armX(&me->timeEvt,
        BSP_TICKS_PER_SEC/2,
        BSP_TICKS_PER_SEC/2);
    return Q_TRAN(&Blink_state_Led_Off);
}
/*.${AOs::Blink::SM::state_Led_Off} ........................................*/
QState Blink_state_Led_Off(Blink * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${AOs::Blink::SM::state_Led_Off} */
        case Q_ENTRY_SIG: {
            // Led_Off
            board_led_off();
            status_ = Q_HANDLED();
            break;
        }
        /*.${AOs::Blink::SM::state_Led_Off::TIMEOUT} */
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Blink_state_Led_On);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*.${AOs::Blink::SM::state_Led_On} .........................................*/
QState Blink_state_Led_On(Blink * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${AOs::Blink::SM::state_Led_On} */
        case Q_ENTRY_SIG: {
            // Led_On
            board_led_on();
            status_ = Q_HANDLED();
            break;
        }
        /*.${AOs::Blink::SM::state_Led_On::TIMEOUT} */
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Blink_state_Led_Off);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*.$enddef${AOs::Blink} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${AOs::Blink_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${AOs::Blink_ctor} ......................................................*/
void Blink_ctor(void) {
    Blink *me = (Blink *)AO_Blink;
    QActive_ctor(&me->super, Q_STATE_CAST(&Blink_initial));
    QTimeEvt_ctorX(&me->timeEvt, &me->super, TIMEOUT_SIG, 0U);
}
/*.$enddef${AOs::Blink_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
